### ISSUE TITLE
Downgrade easy-di

### ISSUE THREAD

**Issue by bekwam** [lestard/todomvcFX#1]

**Comment by manuel-mauky** [comment]
Hi,
thanks for the hint. Your are totally right. I've set the version to 0.3.0 which is the latest version.

**Comment by bekwam** [comment]
Great.  I'm not sure what happened to my description.

**Comment by manuel-mauky** [comment]
Sorry, I've missed to fix the version in the other module too. I've done this now with 57850841db. 
It should now compile. 

I've seen that your are working on a tornadofx version? That's really great. Thanks for supporting this project. I'm looking forward to see your example :-)
