### ISSUE TITLE
Tests not running on my machine

### ISSUE THREAD

**Issue by netopyr** [lestard/todomvcFX#14]
I am trying to build an example using the ReduxFX framework. Unfortunately the tests are not running on my machine. Sometimes they are, but most of the time they hang during initialization. I have never used TestFX before, it is likely that I am doing something wrong.

Do I have to do anything special or should I be able to simply run the tests from my IDE?

**Comment by manuel-mauky** [comment]
Hi Michael,
the tests "should" work on the IDE out of the box. As TestFX is a UI-automation framework, you may not move the mouse during the test run. This is a common mistake. 

If this doesn't work: Is there any error message?

**Comment by netopyr** [comment]
No, unfortunately there is no error message. It seems to hang while loading the native library "libawt_lwawt.dylib".

**Comment by manuel-mauky** [comment]
This sounds like a bug in the TestFX library. 

Can you run a simple TestFX test like this:

``` java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import org.junit.Before;
import org.junit.Test;
import org.testfx.api.FxRobot;
import org.testfx.api.FxToolkit;

import static org.testfx.api.FxAssert.verifyThat;
import static org.testfx.matcher.control.LabeledMatchers.hasText;

public class MinimalUiTest extends FxRobot {

    public static class TestApp extends Application {

        @Override
        public void start(Stage primaryStage) throws Exception {
            VBox root = new VBox();
            Label label = new Label("Test");
            label.setId("l1");

            root.getChildren().add(label);

            primaryStage.setScene(new Scene(root));
            primaryStage.show();
        }
    }

    @Before
    public void setup() throws Exception {
        FxToolkit.registerPrimaryStage();

        FxToolkit.setupApplication(TestApp.class);
    }

    @Test
    public void test() {
        verifyThat("#l1", hasText("Test"));
    }
}
```

Maybe you can create an issue in the [TestFX Repo](https://github.com/TestFX/TestFX/issues)?

**Comment by netopyr** [comment]
I did not really figure out the root-cause of this issue, but for some reasons the tests worked when the application was already running... mysterious!
